version: '3.8'

services:
  anime-list-app:
    # Build the image from the Dockerfile in the current directory
    build: .
    # Name the container for easier management
    container_name: my-anime-list
    # Map port 3000 on your computer to port 3000 in the container
    ports:
      - "8545:3000"
    # Mount the 'data' and 'public/anime-covers' directories from your computer
    # into the container. This is VERY IMPORTANT for data persistence.
    volumes:
      - ./data:/app/data
      - ./public/anime-covers:/app/public/anime-covers
    # Ensure the container restarts automatically if it stops or if you reboot your computer
    restart: always
